services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-shorts-app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "11434:11434"

    volumes:
      - .:/app
    # environment:
    #   - ENV=production
    restart: unless-stopped